"""create_studies_table

Revision ID: 5ff22a6812be
Revises: 
Create Date: 2026-06-16 09:20:15.529500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff22a6812be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('referring_doctor', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.Column('study_instance_uid', sa.String(length=64), nullable=True),
    sa.Column('accession_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'reported', 'verified', name='study_status'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('dicom_path', sa.String(length=512), nullable=True),
    sa.Column('ai_report', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_instance_uid')
    )
    op.create_index(op.f('ix_studies_is_urgent'), 'studies', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_studies_modality'), 'studies', ['modality'], unique=False)
    op.create_index(op.f('ix_studies_patient_id'), 'studies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_index(op.f('ix_studies_patient_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_modality'), table_name='studies')
    op.drop_index(op.f('ix_studies_is_urgent'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
