"""add_number_of_images

Revision ID: fea0d4560b18
Revises: 5ff22a6812be
Create Date: 2026-06-16 10:10:17.976675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea0d4560b18'
down_revision: Union[str, Sequence[str], None] = '5ff22a6812be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('studies', sa.Column('number_of_images', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'number_of_images')
    # ### end Alembic commands ###
